sculpin_content_types:
    posts:
        type: path
        permalink: entries/:year/:month/:day/:filename/
        singular_name: entry
        layout: post
        enabled: true
        taxonomies:
            - tags
            - categories
            - authors
